Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 13, 2024 - 07:16:44
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

"GET / HTTP/1.1" 200 2980
"GET /game/ HTTP/1.1" 200 3353
"GET /static/wordle/js/scripts.js HTTP/1.1" 304 0
"POST /game/ HTTP/1.1" 200 53
Game 17: Correct word is nudge, guess is happy
"POST /submit_guess/ HTTP/1.1" 200 278
"GET /game/ HTTP/1.1" 200 3353
"POST /game/ HTTP/1.1" 200 53
Game 18: Correct word is uncap, guess is crane
"POST /submit_guess/ HTTP/1.1" 200 281
Game 18: Correct word is uncap, guess is audio
"POST /submit_guess/ HTTP/1.1" 200 280
"GET /game/ HTTP/1.1" 200 3353
"POST /game/ HTTP/1.1" 200 53
Game 19: Correct word is horse, guess is crane
"POST /submit_guess/ HTTP/1.1" 200 280
"GET /game/ HTTP/1.1" 200 3353
"POST /game/ HTTP/1.1" 200 53
Game 20: Correct word is nudge, guess is crane
"POST /submit_guess/ HTTP/1.1" 200 280
Game 20: Correct word is nudge, guess is crane
"POST /submit_guess/ HTTP/1.1" 200 280
"GET /game/ HTTP/1.1" 200 3353
"POST /game/ HTTP/1.1" 200 53
Game 21: Correct word is coast, guess is wordl
"POST /submit_guess/ HTTP/1.1" 200 279
"GET /game/ HTTP/1.1" 200 3353
"GET /static/users/main.css HTTP/1.1" 200 1373
"GET /static/wordle/css/styles.css HTTP/1.1" 200 3086
"GET /static/wordle/js/scripts.js HTTP/1.1" 200 10461
"GET /static/users/favicon.ico HTTP/1.1" 200 1150
"POST /game/ HTTP/1.1" 200 53
Game 22: Correct word is mayor, guess is hurde
"POST /submit_guess/ HTTP/1.1" 200 279
"GET /game/ HTTP/1.1" 200 3353
"GET /static/wordle/js/scripts.js HTTP/1.1" 200 10485
"GET /game/ HTTP/1.1" 200 3353
"GET /static/wordle/js/scripts.js HTTP/1.1" 200 10485
"GET /static/users/main.css HTTP/1.1" 200 1373
"GET /static/wordle/css/styles.css HTTP/1.1" 200 3086
"GET /static/users/favicon.ico HTTP/1.1" 200 1150
"POST /game/ HTTP/1.1" 200 53
Game 23: Correct word is ghost, guess is hurdl
"POST /submit_guess/ HTTP/1.1" 200 279
Game 23: Correct word is ghost, guess is happy
"POST /submit_guess/ HTTP/1.1" 200 279
"GET /game/ HTTP/1.1" 200 3353
"GET /static/wordle/js/scripts.js HTTP/1.1" 200 10464
"POST /game/ HTTP/1.1" 200 53
Game 24: Correct word is horse, guess is happy
"POST /submit_guess/ HTTP/1.1" 200 279
"GET /game/ HTTP/1.1" 200 3355
"GET /static/users/main.css HTTP/1.1" 200 1373
"GET /static/wordle/js/scripts.js HTTP/1.1" 200 10464
"GET /static/wordle/css/styles.css HTTP/1.1" 200 3086
"GET /static/users/favicon.ico HTTP/1.1" 200 1150
"POST /game/ HTTP/1.1" 200 53
Game 25: Correct word is fiber, guess is happy
"POST /submit_guess/ HTTP/1.1" 200 278
Game 25: Correct word is fiber, guess is uncap
"POST /submit_guess/ HTTP/1.1" 200 278
Game 25: Correct word is fiber, guess is pious
"POST /submit_guess/ HTTP/1.1" 200 279
Game 25: Correct word is fiber, guess is fiber
Internal Server Error: /submit_guess/
Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
wordle.models.Leaderboard.DoesNotExist: Leaderboard matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Python311\Lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1048, "Column 'score' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py", line 104, in submit_guess
    update_leaderboard(request.user, is_win)
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py", line 124, in update_leaderboard
    leaderboard_entry, created = Leaderboard.objects.get_or_create(user=user)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 955, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\base.py", line 1071, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\base.py", line 1112, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Python311\Lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'score' cannot be null")
"POST /submit_guess/ HTTP/1.1" 500 221203
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 13, 2024 - 07:30:49
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

"GET /game/ HTTP/1.1" 200 3355
"GET /static/wordle/js/scripts.js HTTP/1.1" 304 0
"POST /game/ HTTP/1.1" 200 53
"POST /game/ HTTP/1.1" 200 53
Game 27: Correct word is uncap, guess is happy
"POST /submit_guess/ HTTP/1.1" 200 281
Game 27: Correct word is uncap, guess is uncap
"POST /submit_guess/ HTTP/1.1" 200 284
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 13, 2024 - 07:48:09
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 13, 2024 - 07:48:31
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 13, 2024 - 07:48:35
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 13, 2024 - 07:48:44
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 13, 2024 - 07:48:48
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

"GET /game/ HTTP/1.1" 200 3355
"GET /static/wordle/js/scripts.js HTTP/1.1" 304 0
"POST /game/ HTTP/1.1" 200 53
Game 28: Correct word is lapel, guess is happy
Internal Server Error: /submit_guess/
Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py", line 76, in submit_guess
    feedback[i]['result'] = 'correct'
    ~~~~~~~~^^^
IndexError: list index out of range
"POST /submit_guess/ HTTP/1.1" 500 91493
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle_gato365\urls.py", line 21, in <module>
    from wordle import views as wordle_views
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py", line 66
    feedback = [{'letter': letter, 'result': 'absent'} for letter in guess_word]
IndentationError: unexpected indent
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 13, 2024 - 07:51:40
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

"GET /game/ HTTP/1.1" 200 3355
"GET /static/wordle/js/scripts.js HTTP/1.1" 304 0
"POST /game/ HTTP/1.1" 200 53
Game 29: Correct word is learn, guess is happy
"POST /submit_guess/ HTTP/1.1" 200 279
Game 29: Correct word is learn, guess is learn
"POST /submit_guess/ HTTP/1.1" 200 284
