Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:11:20
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

"GET / HTTP/1.1" 200 3006
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /static/users/favicon.c88b3cd98b54.ico HTTP/1.1" 200 237
"GET /register/ HTTP/1.1" 200 6951
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\users\forms.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:12:01
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\users\forms.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:12:08
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\users\forms.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle_gato365\urls.py", line 19, in <module>
    from users import views as user_views
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\users\views.py", line 5, in <module>
    from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\users\forms.py", line 12
    email = forms.CharField(widget=forms.())
                                         ^
SyntaxError: invalid syntax
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\users\forms.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:12:25
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\users\forms.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:12:30
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

"GET /register/ HTTP/1.1" 200 6758
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /static/users/favicon.c88b3cd98b54.ico HTTP/1.1" 200 237
STREAM b'IHDR' 16 13
STREAM b'eXIf' 41 68
STREAM b'IDAT' 121 65536
STREAM b'IHDR' 16 13
STREAM b'eXIf' 41 68
STREAM b'IDAT' 121 65536
STREAM b'IHDR' 16 13
STREAM b'eXIf' 41 68
STREAM b'IDAT' 121 65536
"POST /register/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 4019
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
STREAM b'IHDR' 16 13
STREAM b'eXIf' 41 68
STREAM b'IDAT' 121 65536
STREAM b'IHDR' 16 13
STREAM b'eXIf' 41 68
STREAM b'IDAT' 121 65536
"POST /login/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 4644
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /tournament/ HTTP/1.1" 200 3751
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /tournament/4/join/ HTTP/1.1" 200 5183
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"POST /tournament/4/join/ HTTP/1.1" 302 0
Internal Server Error: /tournament/4/lobby/
Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: tournament/tournament_lobby.html
"GET /tournament/4/lobby/ HTTP/1.1" 500 145
"GET /tournament/4/lobby/ HTTP/1.1" 200 7500
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
?: (urls.W010) Your URL pattern '<int:tournament_pk>>/lobby/' [name='tournament_lobby'] has an unmatched '>' bracket.

System check identified 1 issue (0 silenced).
November 03, 2024 - 09:21:11
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Not Found: /tournament/4/lobby/
"GET /tournament/4/lobby/ HTTP/1.1" 404 179
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:21:23
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

"GET /tournament/4/lobby/ HTTP/1.1" 200 7500
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /static/users/favicon.c88b3cd98b54.ico HTTP/1.1" 200 237
"POST /logout/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 4047
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
STREAM b'IHDR' 16 13
STREAM b'eXIf' 41 68
STREAM b'IDAT' 121 65536
STREAM b'IHDR' 16 13
STREAM b'eXIf' 41 68
STREAM b'IDAT' 121 65536
"POST /login/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 4644
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /tournament/ HTTP/1.1" 200 4513
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /tournament/5/lobby/ HTTP/1.1" 200 6584
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /tournament/ HTTP/1.1" 200 4513
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /tournament/5/join/ HTTP/1.1" 200 5183
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"POST /tournament/5/join/ HTTP/1.1" 302 0
"GET /tournament/ HTTP/1.1" 200 4513
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /tournament/5/join/ HTTP/1.1" 200 5183
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /tournament/ HTTP/1.1" 200 4513
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /tournament/5/join/ HTTP/1.1" 200 5183
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:27:31
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

"POST /tournament/5/join/ HTTP/1.1" 302 0
"GET /tournament/ HTTP/1.1" 200 4513
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:30:42
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

"GET /tournament/5/join/ HTTP/1.1" 200 5183
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"POST /tournament/5/join/ HTTP/1.1" 302 0
"GET /tournament/ HTTP/1.1" 200 4513
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"POST /tournament/5/join/ HTTP/1.1" 302 0
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:33:05
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:33:11
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:33:15
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:33:25
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:33:30
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:33:33
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:33:42
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:34:24
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle_gato365\urls.py", line 37, in <module>
    path('tournament/', include('tournament.urls')),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\urls\conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\urls.py", line 2, in <module>
    from . import views
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py", line 94
    logger.in
           ^^
SyntaxError: invalid syntax
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:34:36
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:34:42
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

tournament: The 2nd Dragon - 2024-11-03
"POST /tournament/5/join/ HTTP/1.1" 302 0
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:35:33
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:35:38
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:35:45
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:36:12
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:36:22
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

"GET /tournament/ HTTP/1.1" 200 4513
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /static/users/favicon.c88b3cd98b54.ico HTTP/1.1" 200 237
"GET /tournament/5/join/ HTTP/1.1" 200 5183
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"POST /tournament/5/join/ HTTP/1.1" 302 0
"GET /tournament/5/lobby/ HTTP/1.1" 200 6858
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:39:16
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle_gato365\urls.py", line 37, in <module>
    path('tournament/', include('tournament.urls')),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\urls\conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\urls.py", line 2, in <module>
    from . import views
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py", line 78
    logger.
           ^
SyntaxError: invalid syntax
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\tournament\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
November 03, 2024 - 09:39:24
Django version 5.0.6, using settings 'wordle_gato365.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

User team: 23 - The 2nd Dragon
"GET /tournament/5/lobby/ HTTP/1.1" 200 6858
"GET /static/users/main.fd891fa58cd9.css HTTP/1.1" 200 455
"GET /static/users/images/power_logo.6c79ab5b2274.png HTTP/1.1" 200 36796
"GET /static/users/favicon.c88b3cd98b54.ico HTTP/1.1" 200 237
